spring:
  data:
    mongodb:
      database: JobSeekerDb
      port: 27017
      host: localhost
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  application:
    name: jobSeekerMicroservice
server:
  port: 8087


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8080/eureka/